bonus converter refactor
refactor of the converter code by f1rpo  + some more changes

note - code wont compile - something with:
\CvCity.cpp(11835): error C2664: 'CvCity::isBuildingBonus' : cannot convert parameter 1 from 'BonusTypes' to 'BuildingTypes'